export const cssTokens = {
  commentStart: "/*",
  commentEnd: "*/",
  braceStart: "{",
  braceEnd: "}",
  functionStart: "(",
  functionEnd: ")",
  numberRegex: /^[+-]?(\d*\.\d+|\d+\.?)([Ee][+-]?\d+)?/,
  hexColorCodeRegex: /^([0-9a-fA-F]{3}|[0-9a-fA-F]{4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})\b/,
  functions: new Set([
    "abs", "acos", "asin", "atan", "atan2", "attr", "blur", "brightness",
    "calc", "circle", "clamp", "color", "color-contrast", "color-mix",
    "conic-gradient", "contrast", "cos", "counter", "counters", "cross-fade",
    "cubic-bezier", "drop-shadow", "ellipse", "env", "exp", "fit-content",
    "format", "grayscale", "hsl", "hsla", "hue-rotate", "hwb", "hypot", "image",
    "image-set", "inset", "invert", "lab", "lch", "light-dark",
    "linear-gradient", "log", "matrix", "matrix3d", "max", "min", "minmax",
    "mod", "oklab", "oklch", "opacity", "path", "perspective", "polygon", "pow",
    "radial-gradient", "ray", "rem", "repeat", "repeating-conic-gradient",
    "repeating-linear-gradient", "repeating-radial-gradient", "rgb", "rgba",
    "rotate", "rotate3d", "rotateX", "rotateY", "rotateZ", "round", "saturate",
    "scale", "scale3d", "scaleX", "scaleY", "scaleZ", "sepia", "sign", "sin",
    "skew", "skewX", "skewY", "sqrt", "steps", "symbols", "tan", "translate",
    "translate3d", "translateX", "translateY", "translateZ", "url", "var"
  ]),
  units: new Set([
    "em", "ex", "ch", "rem", "lh", "rlh", "vw", "vh", "vmin", "vmax", "vb", "vi",
    "svw", "svh", "lvw", "lvh", "dvw", "dvh", "cap", "ic", "px", "cm", "mm", "in",
    "pc", "pt", "s", "ms", "deg", "grad", "rad", "turn", "Hz", "kHz", "dpi",
    "dpcm", "dppx", "%", "fr"
  ]),
  colorKeywords: new Set([
    "aliceblue", "antiquewhite", "aqua", "aquamarine", "azure", "beige", "bisque", "black",
    "blanchedalmond", "blue", "blueviolet", "brown", "burlywood", "cadetblue", "chartreuse",
    "chocolate", "coral", "cornflowerblue", "cornsilk", "crimson", "cyan", "darkblue",
    "darkcyan", "darkgoldenrod", "darkgray", "darkgreen", "darkgrey", "darkkhaki",
    "darkmagenta", "darkolivegreen", "darkorange", "darkorchid", "darkred", "darksalmon",
    "darkseagreen", "darkslateblue", "darkslategray", "darkslategrey", "darkturquoise",
    "darkviolet", "deeppink", "deepskyblue", "dimgray", "dimgrey", "dodgerblue", "firebrick",
    "floralwhite", "forestgreen", "fuchsia", "gainsboro", "ghostwhite", "gold", "goldenrod",
    "gray", "green", "greenyellow", "grey", "honeydew", "hotpink", "indianred", "indigo",
    "ivory", "khaki", "lavender", "lavenderblush", "lawngreen", "lemonchiffon", "lightblue",
    "lightcoral", "lightcyan", "lightgoldenrodyellow", "lightgray", "lightgreen", "lightgrey",
    "lightpink", "lightsalmon", "lightseagreen", "lightskyblue", "lightslategray",
    "lightslategrey", "lightsteelblue", "lightyellow", "lime", "limegreen", "linen", "magenta",
    "maroon", "mediumaquamarine", "mediumblue", "mediumorchid", "mediumpurple", "mediumseagreen",
    "mediumslateblue", "mediumspringgreen", "mediumturquoise", "mediumvioletred", "midnightblue",
    "mintcream", "mistyrose", "moccasin", "navajowhite", "navy", "oldlace", "olive", "olivedrab",
    "orange", "orangered", "orchid", "palegoldenrod", "palegreen", "paleturquoise", "palevioletred",
    "papayawhip", "peachpuff", "peru", "pink", "plum", "powderblue", "purple", "rebeccapurple",
    "red", "rosybrown", "royalblue", "saddlebrown", "salmon", "sandybrown", "seagreen", "seashell",
    "sienna", "silver", "skyblue", "slateblue", "slategray", "slategrey", "snow", "springgreen",
    "steelblue", "tan", "teal", "thistle", "tomato", "turquoise", "violet", "wheat", "white",
    "whitesmoke", "yellow", "yellowgreen"
  ]),
  pseudoClasses: new Set([
    "active", "any-link", "blank", "checked", "current", "default", "defined", "dir", "disabled",
    "drop", "empty", "enabled", "first", "first-child", "first-of-type", "fullscreen", "future",
    "focus", "focus-visible", "focus-within", "has", "host", "host-context", "hover", "indeterminate",
    "in-range", "invalid", "is", "lang", "last-child", "last-of-type", "left", "link", "local-link",
    "not", "nth-child", "nth-col", "nth-last-child", "nth-last-col", "nth-last-of-type", "nth-of-type",
    "only-child", "only-of-type", "optional", "out-of-range", "past", "placeholder-shown", "read-only",
    "read-write", "required", "right", "root", "scope", "target", "target-within", "user-invalid",
    "valid", "visited", "where"
  ]),
  pseudoElements: new Set([
    "after", "backdrop", "before", "cue", "cue-region", "first-letter", "first-line", "grammar-error",
    "marker", "part", "placeholder", "selection", "slotted", "spelling-error"
  ]),
  values: new Set([
    "auto", "none", "inherit", "initial", "unset", "solid", "dashed", "dotted",
    "block", "inline", "flex", "grid", "absolute", "relative", "fixed", "hidden",
    "visible", "center", "left", "right", "top", "bottom", "middle", "start", "end",
    "auto-fit"
  ]),
};
