export const cssTokens = {
  commentStart: "/*",
  commentEnd: "*/",
  braceStart: "{",
  braceEnd: "}",
  functionStart: "(",
  functionEnd: ")",
  numberRegex: /^[+-]?(\d*\.\d+|\d+\.?)([Ee][+-]?\d+)?/,
  hexColorCodeRegex: /^([0-9a-fA-F]{3}|[0-9a-fA-F]{4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})\b/,
  functions: new Set([
    "abs", "acos", "asin", "atan", "atan2", "attr", "blur", "brightness",
    "calc", "circle", "clamp", "color", "color-contrast", "color-mix",
    "conic-gradient", "contrast", "cos", "counter", "counters", "cross-fade",
    "cubic-bezier", "drop-shadow", "ellipse", "env", "exp", "fit-content",
    "format", "grayscale", "hsl", "hsla", "hue-rotate", "hwb", "hypot", "image",
    "image-set", "inset", "invert", "lab", "lch", "light-dark",
    "linear-gradient", "log", "matrix", "matrix3d", "max", "min", "minmax",
    "mod", "oklab", "oklch", "opacity", "path", "perspective", "polygon", "pow",
    "radial-gradient", "ray", "rem", "repeat", "repeating-conic-gradient",
    "repeating-linear-gradient", "repeating-radial-gradient", "rgb", "rgba",
    "rotate", "rotate3d", "rotateX", "rotateY", "rotateZ", "round", "saturate",
    "scale", "scale3d", "scaleX", "scaleY", "scaleZ", "sepia", "sign", "sin",
    "skew", "skewX", "skewY", "sqrt", "steps", "symbols", "tan", "translate",
    "translate3d", "translateX", "translateY", "translateZ", "url", "var"
  ]),
  units: new Set([
    "em", "ex", "ch", "rem", "lh", "rlh", "vw", "vh", "vmin", "vmax", "vb", "vi",
    "svw", "svh", "lvw", "lvh", "dvw", "dvh", "cap", "ic", "px", "cm", "mm", "in",
    "pc", "pt", "s", "ms", "deg", "grad", "rad", "turn", "Hz", "kHz", "dpi",
    "dpcm", "dppx", "%", "fr"
  ]),
  colorKeywords: new Set([
    "aliceblue", "antiquewhite", "aqua", "aquamarine", "azure", "beige", "bisque", "black",
    "blanchedalmond", "blue", "blueviolet", "brown", "burlywood", "cadetblue", "chartreuse",
    "chocolate", "coral", "cornflowerblue", "cornsilk", "crimson", "cyan", "darkblue",
    "darkcyan", "darkgoldenrod", "darkgray", "darkgreen", "darkgrey", "darkkhaki",
    "darkmagenta", "darkolivegreen", "darkorange", "darkorchid", "darkred", "darksalmon",
    "darkseagreen", "darkslateblue", "darkslategray", "darkslategrey", "darkturquoise",
    "darkviolet", "deeppink", "deepskyblue", "dimgray", "dimgrey", "dodgerblue", "firebrick",
    "floralwhite", "forestgreen", "fuchsia", "gainsboro", "ghostwhite", "gold", "goldenrod",
    "gray", "green", "greenyellow", "grey", "honeydew", "hotpink", "indianred", "indigo",
    "ivory", "khaki", "lavender", "lavenderblush", "lawngreen", "lemonchiffon", "lightblue",
    "lightcoral", "lightcyan", "lightgoldenrodyellow", "lightgray", "lightgreen", "lightgrey",
    "lightpink", "lightsalmon", "lightseagreen", "lightskyblue", "lightslategray",
    "lightslategrey", "lightsteelblue", "lightyellow", "lime", "limegreen", "linen", "magenta",
    "maroon", "mediumaquamarine", "mediumblue", "mediumorchid", "mediumpurple", "mediumseagreen",
    "mediumslateblue", "mediumspringgreen", "mediumturquoise", "mediumvioletred", "midnightblue",
    "mintcream", "mistyrose", "moccasin", "navajowhite", "navy", "oldlace", "olive", "olivedrab",
    "orange", "orangered", "orchid", "palegoldenrod", "palegreen", "paleturquoise", "palevioletred",
    "papayawhip", "peachpuff", "peru", "pink", "plum", "powderblue", "purple", "rebeccapurple",
    "red", "rosybrown", "royalblue", "saddlebrown", "salmon", "sandybrown", "seagreen", "seashell",
    "sienna", "silver", "skyblue", "slateblue", "slategray", "slategrey", "snow", "springgreen",
    "steelblue", "tan", "teal", "thistle", "tomato", "turquoise", "violet", "wheat", "white",
    "whitesmoke", "yellow", "yellowgreen"
  ]),
  pseudoClasses: new Set([
    "active", "any-link", "blank", "checked", "current", "default", "defined", "dir", "disabled",
    "drop", "empty", "enabled", "first", "first-child", "first-of-type", "fullscreen", "future",
    "focus", "focus-visible", "focus-within", "has", "host", "host-context", "hover", "indeterminate",
    "in-range", "invalid", "is", "lang", "last-child", "last-of-type", "left", "link", "local-link",
    "not", "nth-child", "nth-col", "nth-last-child", "nth-last-col", "nth-last-of-type", "nth-of-type",
    "only-child", "only-of-type", "optional", "out-of-range", "past", "placeholder-shown", "read-only",
    "read-write", "required", "right", "root", "scope", "target", "target-within", "user-invalid",
    "valid", "visited", "where"
  ]),
  pseudoElements: new Set([
    "after", "backdrop", "before", "cue", "cue-region", "first-letter", "first-line", "grammar-error",
    "marker", "part", "placeholder", "selection", "slotted", "spelling-error"
  ]),
  values: new Set([
    "auto", "none", "inherit", "initial", "unset", "solid", "dashed", "dotted",
    "block", "inline", "flex", "grid", "absolute", "relative", "fixed", "hidden",
    "visible", "center", "left", "right", "top", "bottom", "middle", "start", "end",
    "auto-fit"
  ]),
  properties: new Set([
    "accent-color", "align-content", "align-items", "align-self", "alignment-baseline",
    "all", "anchor-name", "animation", "animation-composition", "animation-delay",
    "animation-direction", "animation-duration", "animation-fill-mode",
    "animation-iteration-count", "animation-name", "animation-play-state",
    "animation-range", "animation-range-end", "animation-range-start",
    "animation-timeline", "animation-timing-function", "appearance", "aspect-ratio",
    "backdrop-filter", "backface-visibility", "background", "background-attachment",
    "background-blend-mode", "background-clip", "background-color", "background-image",
    "background-origin", "background-position", "background-position-x",
    "background-position-y", "background-repeat", "background-size", "baseline-shift",
    "border", "border-bottom", "border-bottom-color", "border-bottom-left-radius",
    "border-bottom-right-radius", "border-bottom-style", "border-bottom-width",
    "border-collapse", "border-color", "border-image", "border-image-outset",
    "border-image-repeat", "border-image-slice", "border-image-source",
    "border-image-width", "border-left", "border-left-color", "border-left-style",
    "border-left-width", "border-radius", "border-right", "border-right-color",
    "border-right-style", "border-right-width", "border-spacing", "border-style",
    "border-top", "border-top-color", "border-top-left-radius", "border-top-right-radius",
    "border-top-style", "border-top-width", "border-width", "bottom", "box-align",
    "box-decoration-break", "box-direction", "box-flex", "box-flex-group", "box-lines",
    "box-ordinal-group", "box-orient", "box-pack", "box-shadow", "box-sizing",
    "break-after", "break-before", "break-inside", "caption-side", "caret-color",
    "clear", "clip", "clip-path", "clip-rule", "color", "color-interpolation",
    "color-interpolation-filters", "color-profile", "color-rendering", "color-scheme",
    "column-count", "column-fill", "column-gap", "column-rule", "column-rule-color",
    "column-rule-style", "column-rule-width", "column-span", "column-width", "columns",
    "contain", "contain-intrinsic-height", "contain-intrinsic-size",
    "contain-intrinsic-width", "container", "container-name", "container-type",
    "content", "content-visibility", "counter-increment", "counter-reset",
    "counter-set", "cue", "cue-after", "cue-before", "cursor", "cx", "cy", "display",
    "dominant-baseline", "empty-cells", "enable-background", "field-sizing", "fill",
    "fill-opacity", "fill-rule", "filter", "flex", "flex-basis", "flex-direction",
    "flex-flow", "flex-grow", "flex-shrink", "flex-wrap", "float", "flood-color",
    "flood-opacity", "flow", "font", "font-display", "font-family",
    "font-feature-settings", "font-kerning", "font-language-override",
    "font-optical-sizing", "font-palette", "font-size", "font-size-adjust",
    "font-smooth", "font-smoothing", "font-stretch", "font-style", "font-synthesis",
    "font-synthesis-position", "font-synthesis-small-caps", "font-synthesis-style",
    "font-synthesis-weight", "font-variant", "font-variant-alternates",
    "font-variant-caps", "font-variant-east-asian", "font-variant-emoji",
    "font-variant-ligatures", "font-variant-numeric", "font-variant-position",
    "font-variation-settings", "font-weight", "forced-color-adjust", "gap",
    "glyph-orientation-horizontal", "glyph-orientation-vertical", "grid", "grid-area",
    "grid-auto-columns", "grid-auto-flow", "grid-auto-rows", "grid-column",
    "grid-column-end", "grid-column-start", "grid-gap", "grid-row", "grid-row-end",
    "grid-row-start", "grid-template", "grid-template-areas", "grid-template-columns",
    "grid-template-rows", "hanging-punctuation", "height", "hyphenate-character",
    "hyphenate-limit-chars", "hyphens", "icon", "image-orientation", "image-rendering",
    "image-resolution", "ime-mode", "initial-letter", "initial-letter-align",
    "inset", "inset-area", "isolation", "justify-content", "justify-items",
    "justify-self", "kerning", "left", "letter-spacing", "lighting-color", "line-break",
    "line-height", "line-height-step", "list-style", "list-style-image",
    "list-style-position", "list-style-type", "margin", "margin-bottom", "margin-left",
    "margin-right", "margin-top", "margin-trim", "marker", "marker-end", "marker-mid",
    "marker-start", "marks", "mask", "mask-border", "mask-border-mode",
    "mask-border-outset", "mask-border-repeat", "mask-border-slice",
    "mask-border-source", "mask-border-width", "mask-clip", "mask-composite",
    "mask-image", "mask-mode", "mask-origin", "mask-position", "mask-repeat",
    "mask-size", "mask-type", "masonry-auto-flow", "math-depth", "math-shift",
    "math-style", "max-height", "max-width", "min-height", "min-width",
    "mix-blend-mode", "nav-down", "nav-index", "nav-left", "nav-right", "nav-up",
    "none", "normal", "object-fit", "object-position", "offset", "offset-anchor",
    "offset-distance", "offset-path", "offset-position", "offset-rotate", "opacity",
    "order", "orphans", "outline", "outline-color", "outline-offset", "outline-style",
    "outline-width", "overflow", "overflow-anchor", "overflow-clip-margin",
    "overflow-wrap", "overflow-x", "overflow-y", "overlay", "overscroll-behavior",
    "overscroll-behavior-x", "overscroll-behavior-y", "padding", "padding-bottom",
    "padding-left", "padding-right", "padding-top", "page", "page-break-after",
    "page-break-before", "page-break-inside", "paint-order", "pause", "pause-after",
    "pause-before", "perspective", "perspective-origin", "place-content",
    "place-items", "place-self", "pointer-events", "position", "position-anchor",
    "position-visibility", "print-color-adjust", "quotes", "r", "resize", "rest",
    "rest-after", "rest-before", "right", "rotate", "row-gap", "ruby-align",
    "ruby-position", "scale", "scroll-behavior", "scroll-margin", "scroll-margin-bottom",
    "scroll-margin-left", "scroll-margin-right", "scroll-margin-top", "scroll-padding",
    "scroll-padding-bottom", "scroll-padding-left", "scroll-padding-right",
    "scroll-padding-top", "scroll-snap-align", "scroll-snap-stop", "scroll-snap-type",
    "scroll-timeline", "scroll-timeline-axis", "scroll-timeline-name",
    "scrollbar-color", "scrollbar-gutter", "scrollbar-width", "shape-image-threshold",
    "shape-margin", "shape-outside", "shape-rendering", "speak", "speak-as", "src",
    "stop-color", "stop-opacity", "stroke", "stroke-dasharray", "stroke-dashoffset",
    "stroke-linecap", "stroke-linejoin", "stroke-miterlimit", "stroke-opacity",
    "stroke-width", "tab-size", "table-layout", "text-align", "text-align-all",
    "text-align-last", "text-anchor", "text-combine-upright", "text-decoration",
    "text-decoration-color", "text-decoration-line", "text-decoration-skip",
    "text-decoration-skip-ink", "text-decoration-style", "text-decoration-thickness",
    "text-emphasis", "text-emphasis-color", "text-emphasis-position",
    "text-emphasis-style", "text-indent", "text-justify", "text-orientation",
    "text-overflow", "text-rendering", "text-shadow", "text-size-adjust",
    "text-transform", "text-underline-offset", "text-underline-position", "text-wrap",
    "text-wrap-mode", "text-wrap-style", "timeline-scope", "top", "touch-action",
    "transform", "transform-box", "transform-origin", "transform-style", "transition",
    "transition-behavior", "transition-delay", "transition-duration",
    "transition-property", "transition-timing-function", "translate", "user-modify",
    "user-select", "vector-effect", "vertical-align", "view-timeline",
    "view-timeline-axis", "view-timeline-inset", "view-timeline-name",
    "view-transition-name", "visibility", "voice-balance", "voice-duration",
    "voice-family", "voice-pitch", "voice-range", "voice-rate", "voice-stress",
    "voice-volume", "white-space", "white-space-collapse", "widows", "width",
    "will-change", "word-break", "word-spacing", "word-wrap", "x", "y", "z-index",
    "zoom"
  ]),
  logicalProperties: new Set([
    "block-size", "border-block", "border-block-color", "border-block-end",
    "border-block-end-color", "border-block-end-style", "border-block-end-width",
    "border-block-start", "border-block-start-color", "border-block-start-style",
    "border-block-start-width", "border-block-style", "border-block-width",
    "border-end-end-radius", "border-end-start-radius", "border-inline",
    "border-inline-color", "border-inline-end", "border-inline-end-color",
    "border-inline-end-style", "border-inline-end-width", "border-inline-start",
    "border-inline-start-color", "border-inline-start-style",
    "border-inline-start-width", "border-inline-style", "border-inline-width",
    "border-start-end-radius", "border-start-start-radius",
    "contain-intrinsic-block-size", "contain-intrinsic-inline-size", "direction",
    "inline-size", "inset-block", "inset-block-end", "inset-block-start",
    "inset-inline", "inset-inline-end", "inset-inline-start", "margin-block",
    "margin-block-end", "margin-block-start", "margin-inline", "margin-inline-end",
    "margin-inline-start", "max-block-size", "max-inline-size", "min-block-size",
    "min-inline-size", "overflow-block", "overflow-inline", "overscroll-behavior-block",
    "overscroll-behavior-inline", "padding-block", "padding-block-end",
    "padding-block-start", "padding-inline", "padding-inline-end",
    "padding-inline-start", "scroll-margin-block", "scroll-margin-block-end",
    "scroll-margin-block-start", "scroll-margin-inline", "scroll-margin-inline-end",
    "scroll-margin-inline-start", "scroll-padding-block", "scroll-padding-block-end",
    "scroll-padding-block-start", "scroll-padding-inline", "scroll-padding-inline-end",
    "scroll-padding-inline-start", "unicode-bidi", "writing-mode"
  ]),
};
